name: Build blog
on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install hexo-cli -g
      - run: npm ci
      - run: hexo generate
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          CLEAN: true
          BRANCH: gh-pages
          FOLDER: public/
